import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';
import 'package:nus/features/income/application/income_source_repository.dart';
import 'package:nus/features/income/domain/income_source.dart';
import 'package:nus/features/obligations/application/obligation_repository.dart';
import 'package:nus/features/obligations/application/obligation_service.dart';
import 'package:nus/features/obligations/domain/obligation.dart';
import 'package:nus/features/obligations/presentation/obligation_management_page.dart';
import 'package:nus/features/onboarding/domain/household_profile.dart';
import 'package:nus/features/onboarding/presentation/financial_dashboard_page.dart';

Obligation ob({String? id='o1',String userId='u1',String name='إيجار',String type='rent',int amount=3000,String currencyCode='EGP',String frequency='monthly',bool enabled=true})=>Obligation(id:id,userId:userId,name:name,type:type,amount:amount,currencyCode:currencyCode,frequency:frequency,enabled:enabled,createdAt:DateTime.utc(2026,9,1),updatedAt:DateTime.utc(2026,9,1));
IncomeSource inc({int amount=10000})=>IncomeSource(id:'i1',userId:'u1',name:'مرتب',sourceType:'salary',amount:amount,currencyCode:'EGP',frequency:'monthly',enabled:true,createdAt:DateTime.utc(2026,9,1),updatedAt:DateTime.utc(2026,9,1));
class FakeObligationRepository implements ObligationRepository { final Map<String,Obligation> store={}; Object? listFailure,createFailure,updateFailure,deleteFailure,toggleFailure; int createCalls=0,updateCalls=0,deleteCalls=0,toggleCalls=0; @override Future<List<Obligation>> list(String u) async {if(listFailure!=null)throw listFailure!; final x=store.values.where((v)=>v.userId==u).toList()..sort((a,b)=>a.createdAt.compareTo(b.createdAt)); return x;} @override Future<Obligation> create(Obligation o) async {createCalls++;if(createFailure!=null)throw createFailure!;store[o.id??'new']=o;return o;} @override Future<Obligation> update(Obligation o) async {updateCalls++;if(updateFailure!=null)throw updateFailure!;if(o.id==null||!store.containsKey(o.id))throw StateError('missing');store[o.id!]=o;return o;} @override Future<void> delete(String u,String id) async {deleteCalls++;if(deleteFailure!=null)throw deleteFailure!;store.removeWhere((k,v)=>k==id&&v.userId==u);} @override Future<Obligation> setEnabled(String u,String id,bool e) async {toggleCalls++;if(toggleFailure!=null)throw toggleFailure!;final o=store[id];if(o==null||o.userId!=u)throw StateError('missing');final x=o.copyWith(enabled:e);store[id]=x;return x;}}
class FakeIncomeRepository implements IncomeSourceRepository {final Map<String,IncomeSource> store={}; Object? failure; @override Future<List<IncomeSource>> list(String u) async {if(failure!=null)throw failure!;return store.values.where((v)=>v.userId==u).toList();} @override Future<IncomeSource> create(IncomeSource s)=>Future.value(s); @override Future<IncomeSource> update(IncomeSource s)=>Future.value(s); @override Future<void> delete(String u,String id)=>Future.value(); @override Future<IncomeSource> setEnabled(String u,String id,bool e)=>Future.value(inc());}
class NoopObligationRepository implements ObligationRepository {const NoopObligationRepository(); @override Future<List<Obligation>> list(String u)=>Future.value(const []); @override Future<Obligation> create(Obligation o)=>Future.value(o); @override Future<Obligation> update(Obligation o)=>Future.value(o); @override Future<void> delete(String u,String id)=>Future.value(); @override Future<Obligation> setEnabled(String u,String id,bool e)=>Future.value(ob(id:id,enabled:e));}
Widget app(Widget child)=>MaterialApp(theme:ThemeData(useMaterial3:true),home:Directionality(textDirection:TextDirection.rtl,child:child));
const profile=HouseholdProfile(userId:'u1',countryCode:'EG',region:'Cairo',currencyCode:'EGP',householdSize:3,adults:2,children:1,housingType:'rent',incomeFrequency:'monthly',monthlyIncome:10000,recurringObligations:3000);
void main(){
 test('domain rejects invalid values',(){expect(()=>ob(name:''),throwsArgumentError);expect(()=>ob(amount:0),throwsArgumentError);expect(()=>ob(amount:-1),throwsArgumentError);expect(()=>ob(currencyCode:'EG'),throwsArgumentError);expect(()=>ob(type:'bad'),throwsArgumentError);expect(()=>ob(frequency:'irregular'),throwsArgumentError);});
 test('normalization matches income semantics',(){expect(ob(amount:1000,frequency:'monthly').normalizedMonthlyAmount,1000);expect(ob(amount:1000,frequency:'weekly').normalizedMonthlyAmount,4333);expect(ob(amount:20000,frequency:'biweekly').normalizedMonthlyAmount,43333);expect(ob(amount:30000,frequency:'quarterly').normalizedMonthlyAmount,10000);expect(ob(amount:120000,frequency:'yearly').normalizedMonthlyAmount,10000);expect(ob(amount:1,frequency:'weekly').normalizedMonthlyAmount,4);});
 test('aggregation is deterministic and filters disabled/currency',(){const s=ObligationService(repository:NoopObligationRepository());expect(s.totalMonthlyObligations([ob(),ob(id:'w',amount:1000,frequency:'weekly'),ob(id:'off',amount:5000,enabled:false),ob(id:'usd',amount:8000,currencyCode:'USD')],currencyCode:'EGP'),7333);});
 test('repository CRUD ownership and failures propagate',() async {final r=FakeObligationRepository();await r.create(ob());r.store['u2']=ob(id:'u2',userId:'u2');expect((await r.list('u1')).length,1);await r.update(ob(amount:3500));expect(r.store['o1']!.amount,3500);await r.setEnabled('u1','o1',false);expect(r.store['o1']!.enabled,isFalse);await r.delete('u1','o1');expect(r.store.containsKey('u2'),isTrue);r.createFailure=StateError('x');expect(r.create(ob()),throwsStateError);r.createFailure=null;r.updateFailure=StateError('x');expect(r.update(ob()),throwsStateError);r.updateFailure=null;r.toggleFailure=StateError('x');expect(r.setEnabled('u2','u2',true),throwsStateError);r.deleteFailure=StateError('x');expect(r.delete('u2','u2'),throwsStateError);});
 testWidgets('obligation UI exposes list/add/edit/toggle/delete and load failure',(t) async {final r=FakeObligationRepository()..store['o1']=ob();await t.pumpWidget(app(ObligationManagementPage(userId:'u1',householdCurrencyCode:'EGP',service:ObligationService(repository:r))));await t.pumpAndSettle();expect(find.text('إيجار'),findsOneWidget);expect(find.byType(FloatingActionButton),findsOneWidget);await t.tap(find.byType(FloatingActionButton));await t.pumpAndSettle();await t.enterText(find.byType(TextField).first,'مدرسة');await t.enterText(find.byType(TextField).at(1),'2000');await t.tap(find.text('حفظ'));await t.pumpAndSettle();expect(r.createCalls,1);await t.tap(find.byType(PopupMenuButton<String>).first);await t.pumpAndSettle();expect(find.text('تعديل'),findsOneWidget);});
 testWidgets('dashboard uses obligation engine, not profile aggregate',(t) async {final r=FakeObligationRepository()..store['legacy']=ob(id:'legacy',name:'قديم',type:'legacy',amount:7000)..store['rent']=ob(id:'rent',amount:3000);final ir=FakeIncomeRepository()..store['i1']=inc();await t.pumpWidget(app(FinancialDashboardPage(profile:profile,obligationService:ObligationService(repository:r),incomeRepository:ir)));await t.pumpAndSettle();expect(find.text('10,000 EGP'),findsNWidgets(2));expect(find.text('0 EGP'),findsOneWidget);expect(find.text('3,000 EGP'),findsNothing);expect(find.text('7,000 EGP'),findsNothing);});
 testWidgets('dashboard obligation failure is explicit',(t) async {final r=FakeObligationRepository()..listFailure=StateError('offline');final ir=FakeIncomeRepository()..store['i1']=inc();await t.pumpWidget(app(FinancialDashboardPage(profile:profile,obligationService:ObligationService(repository:r),incomeRepository:ir)));await t.pumpAndSettle();expect(find.text('غير متاح'),findsAtLeastNWidgets(1));expect(find.textContaining('لن نعرض رقمًا قديمًا'),findsOneWidget);});
}
