import 'package:flutter/material.dart';

import '../../expenses/application/expense_lifecycle_service.dart';
import '../../expenses/presentation/household_expense_manager_page.dart';
import '../../income/application/income_source_service.dart';
import '../../income/application/income_source_repository.dart';
import '../../income/data/supabase_income_source_repository.dart';
import '../../income/domain/income_source.dart';
import '../../income/presentation/income_management_page.dart';
import '../../obligations/application/obligation_service.dart';
import '../../obligations/data/supabase_obligation_repository.dart';
import '../../obligations/domain/obligation.dart';
import '../../obligations/presentation/obligation_management_page.dart';
import '../domain/household_profile.dart';

class FinancialDashboardPage extends StatefulWidget {
  const FinancialDashboardPage({super.key,required this.profile,this.incomeRepository,this.obligationService,this.expenseService,this.onOpenGeneralHome,this.onSignOut});
  final HouseholdProfile profile; final IncomeSourceRepository? incomeRepository; final ObligationService? obligationService; final ExpenseLifecycleService? expenseService; final void Function(BuildContext context)? onOpenGeneralHome; final VoidCallback? onSignOut;
  @override State<FinancialDashboardPage> createState()=>_FinancialDashboardPageState();
}
class _FinancialDashboardPageState extends State<FinancialDashboardPage>{
  late final IncomeSourceService _incomeService=IncomeSourceService(repository:widget.incomeRepository??const SupabaseIncomeSourceRepository());
  late final ObligationService _obligationService=widget.obligationService??const ObligationService(repository:SupabaseObligationRepository());
  List<IncomeSource> _incomeSources=const []; List<Obligation> _obligations=const []; bool _incomeLoading=true,_obligationsLoading=true; String? _incomeError,_obligationsError;
  @override void initState(){super.initState();_loadIncome();_loadObligations();}
  Future<void> _loadIncome() async{setState(()=>_incomeLoading=true);try{final s=await _incomeService.list(widget.profile.userId);if(!mounted)return;setState((){_incomeSources=s;_incomeLoading=false;_incomeError=null;});}catch(_){if(!mounted)return;setState((){_incomeSources=const [];_incomeLoading=false;_incomeError='مصادر الدخل التفصيلية غير متاحة الآن؛ بنحافظ على دخل إعداد البيت المحفوظ.';});}}
  Future<void> _loadObligations() async{setState(()=>_obligationsLoading=true);try{final o=await _obligationService.list(widget.profile.userId);if(!mounted)return;setState((){_obligations=o;_obligationsLoading=false;_obligationsError=null;});}catch(_){if(!mounted)return;setState((){_obligations=const [];_obligationsLoading=false;_obligationsError='الالتزامات غير متاحة الآن. لن نعرض رقمًا قديمًا على أنه الإجمالي الحقيقي.';});}}
  int get _income=>_incomeSources.isEmpty?widget.profile.monthlyIncome:_incomeService.totalMonthlyIncome(_incomeSources,currencyCode:widget.profile.currencyCode);
  int get _obligations=>_obligationsError==null?_obligationService.totalMonthlyObligations(_obligations,currencyCode:widget.profile.currencyCode):0;
  int get _remaining=>_income-_obligations;
  String _format(int v){final t=v.abs().toString(),p=<String>[];for(var i=t.length;i>0;i-=3){final s=i>3?i-3:0;p.insert(0,t.substring(s,i));}return '${v<0?'-':''}${p.join(',')}';} String _money(int v)=>'${_format(v)} ${widget.profile.currencyCode}';
  Future<void> _openIncomeManagement() async{await Navigator.of(context).push<bool>(MaterialPageRoute(builder:(_)=>IncomeManagementPage(userId:widget.profile.userId,householdCurrencyCode:widget.profile.currencyCode,service:_incomeService)));if(mounted)await _loadIncome();}
  Future<void> _openObligationManagement() async{await Navigator.of(context).push<bool>(MaterialPageRoute(builder:(_)=>ObligationManagementPage(userId:widget.profile.userId,householdCurrencyCode:widget.profile.currencyCode,service:_obligationService)));if(mounted)await _loadObligations();}
  @override Widget build(BuildContext context){final scheme=Theme.of(context).colorScheme;final unavailable=_obligationsError!=null;final positive=_remaining>=0;return Scaffold(appBar:AppBar(title:const Text('حالتي المالية',style:TextStyle(fontWeight:FontWeight.w900)),actions:[if(widget.onSignOut!=null)IconButton(tooltip:'تسجيل الخروج',onPressed:widget.onSignOut,icon:const Icon(Icons.logout_rounded))]),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,12,20,32),children:[Text('دي نقطة البداية الحقيقية لاقتصاد بيتك.',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:6),Text('${widget.profile.householdSize} أفراد · ${widget.profile.adults} بالغين · ${widget.profile.children} أطفال · ${widget.profile.currencyCode}'),const SizedBox(height:18),_card(context,'الدخل الشهري',_money(_income),Icons.account_balance_wallet_outlined,_incomeLoading,_incomeError,'إدارة مصادر الدخل',_incomeLoading?null:_openIncomeManagement),const SizedBox(height:12),_card(context,'الالتزامات الشهرية',unavailable?'غير متاح':_money(_obligations),Icons.receipt_long_rounded,_obligationsLoading,_obligationsError,'إدارة الالتزامات',_obligationsLoading?null:_openObligationManagement,_loadObligations),const SizedBox(height:12),Card(child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[CircleAvatar(backgroundColor:positive?scheme.primaryContainer:scheme.errorContainer,foregroundColor:positive?scheme.onPrimaryContainer:scheme.onErrorContainer,child:Icon(positive?Icons.savings_outlined:Icons.warning_amber_rounded)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('المتبقي بعد الالتزامات',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:4),Text(unavailable?'غير متاح':_money(_remaining),style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900,color:unavailable?scheme.onSurface:(positive?scheme.primary:scheme.error))) ]))]))),const SizedBox(height:12),if(widget.expenseService!=null)FilledButton.icon(onPressed:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>HouseholdExpenseManagerPage(service:widget.expenseService!,isArabic:true))),icon:const Icon(Icons.receipt_long_rounded),label:const Text('إدارة مصروفات البيت')),if(widget.onOpenGeneralHome!=null)...[const SizedBox(height:10),OutlinedButton.icon(onPressed:()=>widget.onOpenGeneralHome!(context),icon:const Icon(Icons.apps_rounded),label:const Text('فتح باقي أدوات NUS'))],const SizedBox(height:10),Text('الأرقام الأساسية هنا تأتي من محركات الدخل والالتزامات، والبيانات القديمة محفوظة للتوافق فقط.',textAlign:TextAlign.center,style:Theme.of(context).textTheme.bodySmall)])) );}
  Widget _card(BuildContext c,String title,String value,IconData icon,bool loading,String? error,String actionLabel,VoidCallback? onAction,[VoidCallback? retry])=>Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[CircleAvatar(child:Icon(icon)),const SizedBox(width:12),Expanded(child:Text(title,style:Theme.of(c).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w800)))]),const SizedBox(height:6),Text(value,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),if(loading)const Padding(padding:EdgeInsets.only(top:8),child:LinearProgressIndicator()),if(error!=null)...[const SizedBox(height:8),Text(error,style:Theme.of(c).textTheme.bodySmall),if(retry!=null)TextButton.icon(onPressed:retry,icon:const Icon(Icons.refresh_rounded),label:const Text('إعادة المحاولة'))],const SizedBox(height:12),FilledButton.icon(onPressed:onAction,icon:const Icon(Icons.open_in_new_rounded),label:Text(actionLabel))])));
}
